### ISSUE TITLE
QueryBuilder issue when having array or nested where clause.

### ISSUE THREAD

**Issue by dankostov** [mghoneimy/php-graphql-client#25]
I am using your plugin to query graphql api and i can't find a way to pass array of strings as argument using QueryBuilder and RawObject.

```
$qb->setVariable('providerSlugs', '[String]', true);
$variables['providerSlugs'] = ['provider1', 'provider2']; //This is array e.g. array('provider1', 'provider2')
$qb->setArgument('where', new RawObject( '{providers :{slug : $providerSlugs}}'));

print_r($queryParams->getVariables()); //this prints out : Array ( [limit] => 20 [sort] => rating:desc [providerSlugs] => Array ( [0] => provider1 ) )
$response = $client->runQuery($queryParams->getQuery(), true, $queryParams->getVariables());

```

The result is returned without the filtering, it's just that this particular "where" filter is not taken in mind. The graphql query get constructed correctly, however the where filtering doesn't work when it's executed from the $client. If i execute it from Playground client in the browser, it works fine.

**Comment by mghoneimy** [comment]
Hi @dankostov ,
I will look into this Tuesday
Thank you!

**Comment by dankostov** [comment]
Hi @mghoneimy did you had the chance to look into this? 

Thanks,
Dan

**Comment by mghoneimy** [comment]
Hello @dankostov ,
I took a deeper look at your problem. Tried to reproduce the same scenario with a test API I use for validating the behavior of the package. I setup a very similar format to yours, an input object that contains an array provided as a variable. Unfortunately, everything worked well for me.

If the query is being constructed correctly and the variables are passed correctly, then I suspect the problem is at the GraphQL server you're running your queries against. If the server is maintained by you, I would advise you to debug it, else if it's provided by someone else, please refer to them, seems like it's not behaving correctly.
Happy to answer any other questions you have.

Here's a snippet of the code I used followed by the output from running the query:
```
$qb = new QueryBuilder('State');
$qb->setVariable('states', '[String!]', true);
$variables['states'] = ['Ohio', 'Washington'];
$qb->setArgument('filter', new RawObject( '{name_in: $states}'));
$qb->selectField('name');

print (string) $qb->getQuery();
print_r($client->runQuery($qb, true, $variables)->getData());
```
There's the output:
```
query($states: [String!]!) {
State(filter: {name_in: $states}) {
name
}
}
Array
(
    [State] => Array
        (
            [0] => Array
                (
                    [name] => Washington
                )
            [1] => Array
                (
                    [name] => Ohio
                )
        )
)
```

**Comment by dankostov** [comment]
Thanks, just saw that. I will review my code again, and try to debug it more.

Have a nice holidays!
